name: conference
description: A simple command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.14.4 <3.0.0'

dev_dependencies:
  lints: ^5.1.1

dependencies: 
  http: ^1.3.0
  puppeteer: ^3.17.0
  xml: ^6.5.0
  dartx: 1.2.0